version: "3.9"
services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - "5672:5672"
      # Management UI
      - "15672:15672"
  gateway:
    container_name: gateway
    build:
      context: ../api-gateway
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    env_file: ../api-gateway/configs/.env
    environment:
      # OUTSOURCE SERVICE
      - AUTH_SERVICE_URL=http://auth:3001
      - USER_SERVICE_URL=http://localhost:3002
      - EVENT_SERVICE_URL=http://localhost:3003
      - APPLICATION_SERVICE_URL=http://application:3005
      - NOTIFICATION_SERVICE_URL=http://localhost:3009
    volumes:
      - ../api-gateway/src:/app/src
  auth:
    container_name: auth
    build:
      context: ../auth
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3001:3001
    env_file: ../auth/configs/.env
    depends_on:
      - rabbitmq
    volumes:
      - ../auth/src:/app/src
  application:
    container_name: application
    build:
      context: ../application
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3005:3005
    env_file: ../application/configs/.env
    volumes:
      - ../application/src:/app/src


  
