FROM node:21-alpine3.18

WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY src ./src
COPY private_key.pem ./
COPY /configs/.env configs/.env
RUN ls -a
RUN npm install && npm install -g nodemon

EXPOSE 3001

CMD ["npm", "run", "dev"]